# Generated by Django 4.0 on 2022-01-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.EmailField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
