# Generated by Django 4.0 on 2022-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_registermodel_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='confirm_password',
            field=models.CharField(max_length=30),
        ),
    ]
