# Generated by Django 4.0 on 2022-01-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_cart_customer_orderplace_product_delete_profiledata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registermodel',
        ),
    ]
