# Generated by Django 4.0 on 2022-01-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_delete_registermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('maharastra', 'maharastra'), ('mp', 'mp'), ('goa', 'goa')], max_length=20),
        ),
    ]
