# Generated by Django 4.0.1 on 2022-01-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=5),
        ),
    ]
