# Generated by Django 4.0.1 on 2022-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=200),
        ),
    ]
